"""CWE and NIST SP 800-53 compliance mapping tables for all Dojigiri rules.

Pure data module — maps rule names to CWE IDs and NIST control families.
Used to enrich findings with industry-standard compliance references.

Called by: config.py (Finding.to_dict), report_html.py, semantic/explain.py
Calls into: nothing (pure data, no dojigiri imports)
Data in -> Data out: rule name string -> CWE/NIST identifier strings
"""

from __future__ import annotations  # noqa

# CWE (Common Weakness Enumeration) mappings
# Maps rule names to CWE IDs
CWE_MAP: dict[str, str] = {
    # Universal rules
    "hardcoded-secret": "CWE-798",
    "aws-credentials": "CWE-798",
    "todo-marker": "CWE-546",
    "long-line": "CWE-1078",
    "insecure-http": "CWE-319",
    "sql-injection-execute": "CWE-89",
    "sql-injection-format": "CWE-89",
    "sql-injection-fstring": "CWE-89",
    "sql-injection-concat": "CWE-89",
    "sql-injection-percent": "CWE-89",
    "sql-injection-raw": "CWE-89",
    # Python rules
    "bare-except": "CWE-396",
    "mutable-default": "CWE-1188",
    "none-comparison": "CWE-597",
    "eval-usage": "CWE-95",
    "exec-usage": "CWE-95",
    "open-without-with": "CWE-404",
    "os-system": "CWE-78",
    "shell-true": "CWE-78",
    "subprocess-audit": "CWE-78",
    "star-import": "CWE-1061",
    "assert-statement": "CWE-617",
    "fstring-no-expr": "CWE-1078",
    "pickle-unsafe": "CWE-502",
    "yaml-unsafe": "CWE-502",
    "weak-hash": "CWE-328",
    "weak-random": "CWE-330",
    # JavaScript/TypeScript rules
    "loose-equality": "CWE-597",
    "console-log": "CWE-532",
    "innerhtml": "CWE-79",
    "insert-adjacent-html": "CWE-79",
    "document-write": "CWE-79",
    # Go rules
    "unchecked-error": "CWE-252",
    "fmt-print": "CWE-532",
    # Rust rules
    "unwrap": "CWE-252",
    "expect-panic": "CWE-252",
    "unsafe-block": "CWE-676",
    # Security rules
    "path-traversal": "CWE-22",
    "private-key": "CWE-321",
    "db-connection-string": "CWE-798",
    "logging-sensitive-data": "CWE-532",
    "insecure-crypto": "CWE-327",
    "insecure-ecb-mode": "CWE-327",
    "django-mark-safe": "CWE-79",
    "django-extra-sql": "CWE-89",
    "paramiko-auto-add-policy": "CWE-295",
    "paramiko-exec-command": "CWE-78",
    "weak-rsa-key": "CWE-326",
    "requests-no-timeout": "CWE-400",
    "logging-config-listen": "CWE-94",
    "ssrf-risk": "CWE-918",
    "url-scheme-audit": "CWE-918",
    "ssti-risk": "CWE-1336",
    "xxe-risk": "CWE-611",
    "jwt-insecure": "CWE-345",
    "hardcoded-ip": "CWE-547",
    "unsafe-deserialization": "CWE-502",
    "insecure-tempfile": "CWE-377",
    # Fold 2 additions
    "os-popen": "CWE-78",
    "subprocess-shell": "CWE-78",
    "os-startfile": "CWE-78",
    "insecure-file-permissions": "CWE-732",
    "bind-all-interfaces": "CWE-668",
    "jinja2-autoescape-off": "CWE-79",
    "pycrypto-deprecated": "CWE-327",
    "ssl-wrap-socket": "CWE-295",
    "requests-no-verify": "CWE-295",
    "ssl-verify-disabled": "CWE-295",
    # Fold 4 additions
    "hardcoded-tmp": "CWE-377",
    "hardcoded-password-default": "CWE-798",
    "debug-enabled": "CWE-489",
    "toctou-file-check": "CWE-367",
    # Fold 5 additions
    "archive-slip": "CWE-22",
    "tarfile-open": "CWE-22",
    "unencrypted-ftp": "CWE-319",
    "unencrypted-telnet": "CWE-319",
    "smtp-cleartext": "CWE-319",
    "webbrowser-open": "CWE-601",
    "ctypes-load-library": "CWE-114",
    "rmtree-audit": "CWE-22",
    "dynamic-import": "CWE-502",
    "env-path-injection": "CWE-426",
    "sys-path-modify": "CWE-426",
    # Python OWASP expansion
    "hardcoded-secret-key": "CWE-798",
    "csrf-middleware-disabled": "CWE-352",
    "csrf-exempt": "CWE-352",
    "django-allowed-hosts-wildcard": "CWE-20",
    "django-raw-sql": "CWE-89",
    "unsafe-redirect": "CWE-601",
    "flask-send-file-traversal": "CWE-22",
    "weak-tls-version": "CWE-326",
    "weak-cipher-suite": "CWE-327",
    "empty-password-check": "CWE-521",
    "empty-password-connection": "CWE-521",
    "cors-wildcard": "CWE-942",
    "security-header-disabled": "CWE-693",
    "ssl-redirect-disabled": "CWE-319",
    "zipfile-extract-audit": "CWE-22",
    "session-cookie-insecure": "CWE-614",
    "session-cookie-no-httponly": "CWE-1004",
    # Fold 6 additions
    "compile-usage": "CWE-95",
    "regex-injection": "CWE-1333",
    "http-connection-cleartext": "CWE-319",
    # Fold 7 additions
    "os-exec": "CWE-78",
    "os-spawn": "CWE-78",
    # JavaScript/TypeScript expansion
    "function-constructor": "CWE-95",
    "outerhtml": "CWE-79",
    "proto-access": "CWE-1321",
    "object-assign-merge": "CWE-1321",
    "open-redirect": "CWE-601",
    "insecure-random": "CWE-330",
    "postmessage-no-origin": "CWE-346",
    "regexp-injection": "CWE-1333",
    "insecure-cookie": "CWE-614",
    "jwt-alg-none": "CWE-345",
    "nosql-injection": "CWE-943",
    "js-command-injection": "CWE-78",
    "js-command-injection-template": "CWE-78",
    "js-path-traversal": "CWE-22",
    "js-hardcoded-jwt-secret": "CWE-798",
    "js-tls-reject-unauthorized": "CWE-295",
    "js-tls-env-disable": "CWE-295",
    "debugger-statement": "CWE-489",
    "delete-array": "CWE-704",
    "empty-catch": "CWE-390",
    "alert-usage": "CWE-489",
    "missing-await-hint": "CWE-252",
    "promise-no-catch": "CWE-252",
    "settimeout-string": "CWE-95",
    "prototype-overwrite": "CWE-1321",
    "with-statement": "CWE-398",
    "bitwise-in-condition": "CWE-480",
    "void-zero": "CWE-1078",
    # Go expansion
    "go-sql-sprintf": "CWE-89",
    "go-sql-concat": "CWE-89",
    "go-command-injection": "CWE-78",
    "go-command-injection-ctx": "CWE-78",
    "go-path-traversal": "CWE-22",
    "go-hardcoded-credential": "CWE-798",
    "go-weak-crypto-md5": "CWE-328",
    "go-weak-crypto-sha1": "CWE-328",
    "go-weak-crypto-des": "CWE-327",
    "go-insecure-tls": "CWE-295",
    "go-weak-tls-version": "CWE-326",
    "go-unsafe-pointer": "CWE-676",
    "go-ssrf": "CWE-918",
    "go-open-redirect": "CWE-601",
    "go-defer-in-loop": "CWE-404",
    "go-goroutine-anonymous": "CWE-404",
    "go-nil-map": "CWE-476",
    "go-panic": "CWE-248",
    "go-string-byte-copy": "CWE-1078",
    "go-global-var": "CWE-362",
    # Java-specific rules
    "java-sql-injection": "CWE-89",
    "java-xss": "CWE-79",
    "java-cmdi": "CWE-78",
    "java-ldap-injection": "CWE-90",
    "java-xpath-injection": "CWE-643",
    "java-weak-crypto": "CWE-327",
    "java-weak-hash": "CWE-328",
    "java-weak-random": "CWE-330",
    "java-trust-boundary": "CWE-501",
    "java-insecure-cookie": "CWE-614",
    "java-path-traversal": "CWE-22",
    # Java — Spring Security
    "java-spring-csrf-disabled": "CWE-352",
    "java-spring-permit-all-sensitive": "CWE-862",
    "java-spring-missing-preauthorize": "CWE-862",
    "java-spring-cors-allow-all": "CWE-942",
    "java-spring-weak-password-encoder": "CWE-916",
    "java-spring-security-debug": "CWE-215",
    "java-spring-permit-all-wildcard": "CWE-862",
    # Java — Spring MVC
    "java-spring-open-redirect": "CWE-601",
    "java-spring-missing-valid": "CWE-20",
    "java-spring-unvalidated-forward": "CWE-552",
    "java-spring-path-variable-traversal": "CWE-22",
    # Java — Deserialization
    "java-unsafe-deserialization": "CWE-502",
    "java-xmldecoder-deserialization": "CWE-502",
    "java-snakeyaml-unsafe": "CWE-502",
    "java-kryo-unsafe": "CWE-502",
    "java-xstream-unsafe": "CWE-502",
    # Java — XXE
    "java-xxe-documentbuilder": "CWE-611",
    "java-xxe-saxparser": "CWE-611",
    "java-xxe-xmlreader": "CWE-611",
    "java-xxe-transformer": "CWE-611",
    # Java — SSRF
    "java-ssrf-url": "CWE-918",
    "java-ssrf-httpclient": "CWE-918",
    "java-ssrf-resttemplate": "CWE-918",
    "java-ssrf-webclient": "CWE-918",
    # Java — Cryptography
    "java-ecb-mode": "CWE-327",
    "java-static-iv": "CWE-329",
    "java-weak-key-size": "CWE-326",
    "java-insecure-pbe": "CWE-327",
    "java-md5-sha1-password": "CWE-916",
    "java-null-cipher": "CWE-327",
    "java-static-encryption-key": "CWE-798",
    "java-weak-tls": "CWE-326",
    # Java — File Upload
    "java-unrestricted-upload": "CWE-434",
    "java-upload-original-filename": "CWE-22",
    "java-upload-no-size-limit": "CWE-400",
    # Java — JNDI
    "java-jndi-injection": "CWE-917",
    "java-jndi-lookup-concat": "CWE-917",
    "java-jndi-ldap-rmi": "CWE-917",
    "java-jndi-lookup-variable": "CWE-74",
    # Java — Expression Language
    "java-spel-injection": "CWE-917",
    "java-spel-injection-concat": "CWE-917",
    "java-el-injection": "CWE-917",
    "java-spel-value-annotation": "CWE-917",
    "java-spel-parse-variable": "CWE-917",
    # Java — Logging
    "java-log-injection": "CWE-117",
    "java-log4j-lookup": "CWE-917",
    "java-log-format-string": "CWE-134",
    # Java — Authentication
    "java-hardcoded-password": "CWE-798",
    "java-empty-password": "CWE-258",
    "java-default-credentials": "CWE-798",
    "java-trust-all-certs": "CWE-295",
    "java-hostname-verifier-bypass": "CWE-297",
    # Java — JWT
    "java-jwt-none-algorithm": "CWE-345",
    "java-jwt-missing-expiration": "CWE-613",
    "java-jwt-weak-secret": "CWE-326",
    "java-jwt-no-verification": "CWE-345",
    # Java — Hibernate/HQL
    "java-hql-injection": "CWE-89",
    "java-hql-injection-var": "CWE-89",
    "java-native-query-injection": "CWE-89",
    # Java — XML
    "java-xstream-no-allowlist": "CWE-502",
    "java-dom-parse-no-limits": "CWE-776",
    "java-jaxb-external-entity": "CWE-611",
    # Java — Error Handling
    "java-stacktrace-exposure": "CWE-209",
    "java-verbose-error-response": "CWE-209",
    "java-catch-generic-exception": "CWE-396",
    "java-empty-catch-block": "CWE-390",
    "java-printstacktrace": "CWE-497",
    # Java — Concurrency
    "java-double-checked-locking": "CWE-609",
    "java-non-atomic-check-then-act": "CWE-367",
    "java-toctou-file-check-then-act": "CWE-367",
    "java-async-file-operation": "CWE-367",
    "java-synchronized-on-boxed": "CWE-662",
    # Java — Android
    "java-android-exported-component": "CWE-926",
    "java-android-webview-js": "CWE-749",
    "java-android-cleartext-traffic": "CWE-319",
    "java-android-webview-file-access": "CWE-200",
    "java-android-world-readable": "CWE-732",
    # Java — Kotlin Interop
    "java-kotlin-platform-type": "CWE-476",
    "java-nullable-annotation-missing": "CWE-476",
    # Java — Additional
    "java-template-injection": "CWE-94",
    "java-regex-dos": "CWE-1333",
    "java-unvalidated-redirect-response": "CWE-601",
    "java-header-injection": "CWE-113",
    "java-insecure-ssl-factory": "CWE-295",
    "java-system-exit": "CWE-382",
    "java-thread-sleep-in-sync": "CWE-662",
    "java-unsafe-reflection": "CWE-470",
    "java-insecure-temp-file": "CWE-377",
    "java-runtime-exec": "CWE-78",
    "java-cors-credentials-wildcard": "CWE-942",
    "java-spring-actuator-exposed": "CWE-215",
    "java-deserialization-gadget": "CWE-502",
    "java-insecure-xml-validation": "CWE-611",
    "java-permission-check-missing": "CWE-862",
    "java-unsafe-object-binding": "CWE-915",
    # Semantic/AST rules (detector.py, semantic/)
    "syntax-error": "CWE-670",
    "unused-import": "CWE-561",
    "exception-swallowed": "CWE-390",
    "exception-swallowed-continue": "CWE-390",
    "shadowed-builtin": "CWE-710",
    "shadowed-builtin-param": "CWE-710",
    "type-comparison": "CWE-595",
    "global-keyword": "CWE-1108",
    "unreachable-code": "CWE-561",
    "high-complexity": "CWE-1121",
    "too-many-args": "CWE-1064",
    "empty-exception-handler": "CWE-390",
    # Scope analysis
    "unused-variable": "CWE-563",
    "variable-shadowing": "CWE-710",
    "possibly-uninitialized": "CWE-457",
    # Null safety
    "null-dereference": "CWE-476",
    # Resource analysis
    "resource-leak": "CWE-404",
    # Taint analysis
    "taint-flow": "CWE-20",
    "taint-flow-cross-file": "CWE-20",
    # Code smells
    "god-class": "CWE-1075",
    "feature-envy": "CWE-1075",
    "long-method": "CWE-1080",
    "near-duplicate": "CWE-1041",
    "semantic-clone": "CWE-1041",
    # Graph analysis
    "dead-function": "CWE-561",
    "arg-count-mismatch": "CWE-628",
    "cross-file-issue": "CWE-710",
    # SCA
    "vulnerable-dependency": "CWE-1395",
    # ── Cross-language: Credentials & Secrets ──────────────────────────
    "boto3-hardcoded-key": "CWE-798",
    "flask-secret-hardcoded": "CWE-798",
    "generic-bearer-token": "CWE-798",
    "github-token": "CWE-798",
    "go-static-key": "CWE-798",
    "google-api-key": "CWE-798",
    "hardcoded-api-key": "CWE-798",
    "hardcoded-credential": "CWE-798",
    "hardcoded-jwt-secret": "CWE-798",
    "hardcoded-password": "CWE-798",
    "hardcoded-secret-dict": "CWE-798",
    "lambda-env-secret": "CWE-798",
    "npm-token": "CWE-798",
    "sendgrid-key": "CWE-798",
    "slack-token": "CWE-798",
    "stripe-key": "CWE-798",
    "twilio-key": "CWE-798",
    "base64-secret": "CWE-798",
    "process-env-default-secret": "CWE-798",
    "env-file-committed": "CWE-798",
    "env-var-secret": "CWE-798",
    "password-in-query-string": "CWE-598",
    "password-in-url": "CWE-598",
    # ── Cross-language: SQL Injection ──────────────────────────────────
    "format-string-sql": "CWE-89",
    "knex-raw-interpolation": "CWE-89",
    "sequelize-raw-query": "CWE-89",
    "sql-string-concat": "CWE-89",
    "sql-template-literal": "CWE-89",
    "sqlalchemy-execute-concat": "CWE-89",
    "sqlalchemy-execute-format": "CWE-89",
    "sqlalchemy-execute-fstring": "CWE-89",
    "sqlalchemy-text-format": "CWE-89",
    # ── Cross-language: Command Injection ──────────────────────────────
    "command-shell": "CWE-78",
    "shell-injection": "CWE-78",
    "command-injection": "CWE-78",
    "subprocess-popen-concat": "CWE-78",
    "subprocess-shell-user-input": "CWE-78",
    "async-subprocess-shell": "CWE-78",
    "child-process-spawn-shell": "CWE-78",
    # ── Cross-language: Deserialization ────────────────────────────────
    "deserialization-unsafe": "CWE-502",
    "dill-loads-unsafe": "CWE-502",
    "js-yaml-unsafe-load": "CWE-502",
    "marshal-loads-unsafe": "CWE-502",
    "node-serialize-usage": "CWE-502",
    "pickle-from-request": "CWE-502",
    "serialize-unserialize": "CWE-502",
    "shelve-open-unsafe": "CWE-502",
    "dunder-import-dynamic": "CWE-502",
    "multiprocessing-pickle": "CWE-502",
    "pydantic-arbitrary-types": "CWE-502",
    # ── Cross-language: XSS ───────────────────────────────────────────
    "react-dangerously-set-innerhtml": "CWE-79",
    "react-href-javascript": "CWE-79",
    "react-ref-innerhtml": "CWE-79",
    "raw-html-response": "CWE-79",
    "xss-document-write": "CWE-79",
    "xss-innerhtml": "CWE-79",
    # ── Cross-language: SSRF ──────────────────────────────────────────
    "ssrf-axios-user-url": "CWE-918",
    "ssrf-fetch-user-url": "CWE-918",
    "ssrf-got-user-url": "CWE-918",
    "ssrf-request-user-url": "CWE-918",
    # ── Cross-language: Path Traversal ────────────────────────────────
    "fs-user-controlled-read": "CWE-22",
    "fs-user-controlled-unlink": "CWE-22",
    "fs-user-controlled-write": "CWE-22",
    "zip-slip-extract": "CWE-22",
    "file-open-fstring": "CWE-22",
    # ── Cross-language: Cryptography ──────────────────────────────────
    "crypto-create-cipher": "CWE-327",
    "crypto-des-algorithm": "CWE-327",
    "crypto-ecb-mode": "CWE-327",
    "crypto-ecb-aes-new": "CWE-327",
    "crypto-ecb-java": "CWE-327",
    "insecure-blowfish": "CWE-327",
    "insecure-des": "CWE-327",
    "insecure-rc4": "CWE-327",
    "crypto-weak-random-token": "CWE-330",
    "crypto-md5-hmac": "CWE-328",
    "crypto-weak-hash-md5": "CWE-328",
    "crypto-weak-hash-sha1": "CWE-328",
    "weak-crypto-md5": "CWE-328",
    "weak-crypto-sha1": "CWE-328",
    "weak-hash-md5": "CWE-328",
    "weak-hash-sha1": "CWE-328",
    "hashlib-new-weak": "CWE-328",
    "crypto-static-iv": "CWE-329",
    "crypto-weak-pbkdf2": "CWE-916",
    "bcrypt-low-rounds": "CWE-916",
    "weak-bcrypt-rounds": "CWE-916",
    # ── Cross-language: TLS/SSL ───────────────────────────────────────
    "insecure-ssl-context": "CWE-295",
    "tls-no-verify": "CWE-295",
    "aiohttp-no-verify": "CWE-295",
    "urllib3-no-verify": "CWE-295",
    "ssl-no-hostname-check": "CWE-295",
    # ── Cross-language: CORS ──────────────────────────────────────────
    "cors-reflect-origin": "CWE-942",
    "express-cors-credentials-wildcard": "CWE-942",
    "fastapi-cors-wildcard": "CWE-942",
    "fastapi-credentials-wildcard": "CWE-942",
    # ── Cross-language: CSRF ──────────────────────────────────────────
    "csrf-disabled": "CWE-352",
    # ── Cross-language: Open Redirect ─────────────────────────────────
    "window-open-user-url": "CWE-601",
    # ── Cross-language: Prototype Pollution ────────────────────────────
    "deep-merge-no-proto-check": "CWE-1321",
    "lodash-merge-user-input": "CWE-1321",
    "object-assign-user-input": "CWE-1321",
    "spread-constructor-pollution": "CWE-1321",
    "prototype-pollution-merge": "CWE-1321",
    # ── Cross-language: LDAP / XPath Injection ────────────────────────
    "ldap-injection": "CWE-90",
    "xpath-injection": "CWE-643",
    # ── Cross-language: JWT ───────────────────────────────────────────
    "jwt-none-algorithm": "CWE-345",
    "jwt-no-expiry": "CWE-613",
    # ── Cross-language: Header Injection ──────────────────────────────
    "header-injection": "CWE-113",
    # ── Cross-language: NoSQL Injection ────────────────────────────────
    "mongodb-regex-user-input": "CWE-943",
    "mongodb-where-operator": "CWE-943",
    "mongoose-find-user-object": "CWE-943",
    "nosql-injection-mongodb": "CWE-943",
    # ── Cross-language: Information Disclosure ─────────────────────────
    "nextjs-exposed-server-env": "CWE-200",
    "nextjs-getserversideprops-leak": "CWE-200",
    "nuxt-exposed-runtime-secret": "CWE-200",
    "information-disclosure-stacktrace": "CWE-209",
    "graphql-introspection-enabled": "CWE-200",
    "source-map-in-production": "CWE-200",
    "directory-listing": "CWE-548",
    # ── Cross-language: Debug Left In Code ─────────────────────────────
    "code-interactive-console": "CWE-489",
    "werkzeug-debugger": "CWE-489",
    "dbg-macro": "CWE-489",
    "flask-debug-production": "CWE-489",
    "fastapi-debug-docs": "CWE-489",
    # ── Cross-language: Logging Sensitive Data ─────────────────────────
    "log-credit-card": "CWE-532",
    "log-password-interpolation": "CWE-532",
    "println-in-lib": "CWE-532",
    # ── Cross-language: Timing Attack ──────────────────────────────────
    "timing-attack-comparison": "CWE-208",
    # ── Cross-language: Mass Assignment ────────────────────────────────
    "mass-assignment": "CWE-915",
    "class-manipulation": "CWE-915",
    "setattr-dynamic": "CWE-915",
    # ── Cross-language: ReDoS ──────────────────────────────────────────
    "re-dos-quantifier": "CWE-1333",
    "redos-nested-quantifier": "CWE-1333",
    "regex-dos": "CWE-1333",
    "redos-overlapping-alternation": "CWE-1333",
    # ── Cross-language: File Upload ────────────────────────────────────
    "unvalidated-file-upload": "CWE-434",
    "file-upload-unrestricted": "CWE-434",
    # ── Cross-language: File Permissions ───────────────────────────────
    "file-world-writable": "CWE-732",
    "fs-chmod-world-writable": "CWE-732",
    "s3-public-acl": "CWE-732",
    # ── Cross-language: Resource Management ────────────────────────────
    "forget-leak": "CWE-401",
    "reqwest-no-timeout": "CWE-400",
    "graphql-no-depth-limit": "CWE-400",
    "graphql-no-cost-analysis": "CWE-400",
    "express-bodyparser-no-limit": "CWE-400",
    # ── Cross-language: Race Conditions ────────────────────────────────
    "race-condition-mkdir": "CWE-362",
    "os-link-toctou": "CWE-367",
    # ── Cross-language: Code Injection / Eval ──────────────────────────
    "getattr-user-input": "CWE-95",
    "globals-manipulation": "CWE-94",
    "vm-module-escape": "CWE-94",
    # ── Cross-language: Session ────────────────────────────────────────
    "session-insecure": "CWE-614",
    # ── Cross-language: Cleartext Communication ────────────────────────
    "ftp-no-tls": "CWE-319",
    "python-http-server": "CWE-319",
    "websocket-unencrypted": "CWE-319",
    # ── Cross-language: Misc Security ──────────────────────────────────
    "temp-file-predictable": "CWE-377",
    "file-mkdtemp-ignore": "CWE-377",
    "tempfile-predictable-name": "CWE-377",
    "websocket-no-origin-check": "CWE-346",
    "dns-rebinding-risk": "CWE-350",
    "express-no-helmet": "CWE-693",
    "helmet-csp-unsafe-inline": "CWE-693",
    "express-trust-proxy-true": "CWE-346",
    "express-static-dotfiles": "CWE-548",
    "s3-no-encryption": "CWE-311",
    "subprocess-env-path": "CWE-426",
    "process-exit": "CWE-382",
    "blocking-in-async": "CWE-662",
    "sleep-in-async": "CWE-662",
    "transmute": "CWE-676",
    "raw-pointer-deref": "CWE-676",
    "signal-handler-unsafe": "CWE-676",
    "buffer-alloc-unsafe": "CWE-119",
    "buffer-from-number": "CWE-119",
    # ── Cross-language: Code Quality / Style ───────────────────────────
    "allow-lint": "CWE-710",
    "fixme-critical": "CWE-546",
    "todo-unfinished": "CWE-546",
    "commented-code-block": "CWE-561",
    "box-string": "CWE-1078",
    "box-vec": "CWE-1078",
    "clone-on-copy": "CWE-1078",
    "magic-number": "CWE-1078",
    "mixed-indentation": "CWE-1078",
    "trailing-whitespace": "CWE-1078",
    "rc-refcell-vec": "CWE-1078",
    "recursive-type-no-box": "CWE-1078",
    "string-push-in-loop": "CWE-1078",
    "lossy-conversion": "CWE-704",
    "ts-any-security-context": "CWE-704",
    "ts-double-assertion": "CWE-704",
    "ts-non-null-assertion-chain": "CWE-476",
    # ── TypeScript-specific ────────────────────────────────────────────
    "ts-as-any-cast": "CWE-704",
    "ts-double-cast": "CWE-704",
    "ts-non-null-assertion": "CWE-476",
    "ts-angle-bracket-any": "CWE-704",
    "ts-ignore-comment": "CWE-710",
    "ts-expect-error-bypass": "CWE-710",
    "ts-any-param": "CWE-704",
    "ts-any-return": "CWE-704",
    "ts-excessive-any-annotation": "CWE-704",
    "ts-object-type": "CWE-704",
    "ts-json-parse-assertion": "CWE-20",
    "ts-record-string-any": "CWE-704",
    "ts-type-only-import-runtime": "CWE-20",
    "ts-declare-ambient": "CWE-704",
    "ts-satisfies-no-validation": "CWE-20",
    "ts-unvalidated-external-assertion": "CWE-20",
    "ts-index-signature-any": "CWE-704",
    "ts-nestjs-no-auth-guard": "CWE-306",
    "ts-express-any-body": "CWE-20",
    "ts-unvalidated-dto": "CWE-20",
    "ts-graphql-any-return": "CWE-704",
    "ts-prisma-raw-interpolation": "CWE-89",
    "ts-typeorm-raw-query": "CWE-89",
    "ts-nextjs-unvalidated-params": "CWE-20",
    "ts-react-useeffect-external": "CWE-20",
    "ts-nocheck": "CWE-710",
    "ts-triple-slash-disable": "CWE-710",
    "ts-typeof-object-no-null": "CWE-476",
    "ts-type-predicate-no-narrow": "CWE-704",
    "ts-as-const-mutable": "CWE-471",
    "ts-enum-no-default": "CWE-478",
    "ts-missing-readonly-config": "CWE-471",
    "ts-overload-any-fallback": "CWE-704",
    "ts-generic-any-constraint": "CWE-704",
    "ts-partial-security-type": "CWE-284",
    # ── Rust-specific ──────────────────────────────────────────────────
    "panic-in-lib": "CWE-248",
    "unimplemented-macro": "CWE-248",
    "unreachable-macro": "CWE-248",
    "index-panic": "CWE-248",
    "unwrap-or-default": "CWE-252",
    "mutex-poison": "CWE-667",
    # ── Electron-specific ──────────────────────────────────────────────
    "electron-allow-running-insecure": "CWE-829",
    "electron-context-isolation-off": "CWE-829",
    "electron-node-integration": "CWE-829",
    "electron-websecurity-off": "CWE-829",
    "electron-shell-openexternal": "CWE-78",
    "electron-remote-module": "CWE-829",
    "npm-postinstall-script": "CWE-829",
    "npm-preinstall-script": "CWE-829",
    "npm-dependency-confusion": "CWE-829",
    # ── Django-specific ────────────────────────────────────────────────
    "django-extra-fstring": "CWE-89",
    "django-raw-fstring": "CWE-89",
    "django-rawsql-format": "CWE-89",
    # ── PHP-specific ───────────────────────────────────────────────────
    "php-assert-string": "CWE-95",
    "php-command-injection-backtick": "CWE-78",
    "php-command-injection-exec": "CWE-78",
    "php-command-injection-passthru": "CWE-78",
    "php-command-injection-shell-exec": "CWE-78",
    "php-command-injection-system": "CWE-78",
    "php-command-injection-popen": "CWE-78",
    "php-command-injection-proc-open": "CWE-78",
    "php-create-function": "CWE-95",
    "php-curl-ssl-host-off": "CWE-295",
    "php-curl-ssl-verify-off": "CWE-295",
    "php-eval": "CWE-95",
    "php-extract-globals": "CWE-94",
    "php-file-inclusion-concat": "CWE-98",
    "php-file-inclusion-variable": "CWE-98",
    "php-header-injection": "CWE-113",
    "php-md5-password": "CWE-328",
    "php-preg-replace-e": "CWE-95",
    "php-register-globals": "CWE-94",
    "php-session-fixation": "CWE-384",
    "php-sha1-password": "CWE-328",
    "php-sql-injection-interpolation": "CWE-89",
    "php-sql-injection-mysql": "CWE-89",
    "php-sql-injection-mysqli-concat": "CWE-89",
    "php-sql-injection-pdo-concat": "CWE-89",
    "php-ssrf-file-get-contents": "CWE-918",
    "php-ssrf-curl": "CWE-918",
    "php-strcmp-bypass": "CWE-697",
    "php-type-juggling-password": "CWE-697",
    "php-unserialize": "CWE-502",
    "php-deserialize-phar": "CWE-502",
    "php-weak-encryption": "CWE-327",
    "php-xss-echo": "CWE-79",
    "php-xss-no-escape": "CWE-79",
    "php-error-display": "CWE-209",
    "php-expose-phpinfo": "CWE-200",
    "php-file-upload-no-validation": "CWE-434",
    "php-hardcoded-credentials": "CWE-798",
    "php-mt-rand-security": "CWE-330",
    "php-open-redirect": "CWE-601",
    "php-path-traversal-fopen": "CWE-22",
    "php-path-traversal-unlink": "CWE-22",
    "php-weak-hash-general": "CWE-328",
    "php-xxe-dom": "CWE-611",
    "php-xxe-simplexml": "CWE-611",
    "php-rand-security": "CWE-330",
    # ── C# (.NET) specific ─────────────────────────────────────────────
    "cs-binary-formatter": "CWE-502",
    "cs-cors-allow-credentials-any": "CWE-942",
    "cs-ecb-mode": "CWE-327",
    "cs-ef-raw-sql": "CWE-89",
    "cs-ef-raw-sql-concat": "CWE-89",
    "cs-hardcoded-connection-string": "CWE-798",
    "cs-hardcoded-password": "CWE-798",
    "cs-ldap-injection": "CWE-90",
    "cs-losformatter": "CWE-502",
    "cs-newtonsoft-typenamehandling": "CWE-502",
    "cs-soapformatter": "CWE-502",
    "cs-sql-injection-concat": "CWE-89",
    "cs-sql-injection-format": "CWE-89",
    "cs-ssl-bypass": "CWE-295",
    "cs-weak-crypto-des": "CWE-327",
    "cs-xxe-dtd-enabled": "CWE-611",
    "cs-command-injection": "CWE-78",
    "cs-command-injection-cmd": "CWE-78",
    "cs-command-injection-shell": "CWE-78",
    "cs-cookie-no-httponly": "CWE-1004",
    "cs-cookie-no-secure": "CWE-614",
    "cs-cors-allow-all": "CWE-942",
    "cs-javascript-serializer": "CWE-502",
    "cs-logging-sensitive": "CWE-532",
    "cs-missing-antiforgery": "CWE-352",
    "cs-path-traversal-directory": "CWE-22",
    "cs-path-traversal-file": "CWE-22",
    "cs-regex-injection": "CWE-1333",
    "cs-ssl-check-revocation": "CWE-295",
    "cs-static-iv": "CWE-329",
    "cs-unvalidated-redirect": "CWE-601",
    "cs-weak-hash-md5": "CWE-328",
    "cs-weak-hash-sha1": "CWE-328",
    "cs-weak-password-hash": "CWE-916",
    "cs-xss-html-raw": "CWE-79",
    "cs-xss-htmlstring": "CWE-79",
    "cs-xss-response-write": "CWE-79",
    "cs-xxe-xmldocument": "CWE-611",
    "cs-authorize-bypass": "CWE-862",
    "cs-ssrf-httpclient": "CWE-918",
    "cs-ssrf-webclient": "CWE-918",
    "cs-viewbag-raw": "CWE-79",
    "cs-weak-rng": "CWE-330",
    "cs-xxe-xmlreader": "CWE-611",
    # ── Go expansion (additional) ──────────────────────────────────────
    "go-bcrypt-cost-low": "CWE-916",
    "go-body-not-closed": "CWE-404",
    "go-context-background-http": "CWE-400",
    "go-cookie-no-secure": "CWE-614",
    "go-cors-wildcard": "CWE-942",
    "go-ecb-mode": "CWE-327",
    "go-error-string-compare": "CWE-253",
    "go-filepath-join-dotdot": "CWE-22",
    "go-gob-decode": "CWE-502",
    "go-goroutine-loop-var": "CWE-362",
    "go-http-default-client": "CWE-400",
    "go-ldap-injection": "CWE-90",
    "go-mutex-copy": "CWE-667",
    "go-no-timeout": "CWE-400",
    "go-reflect-call": "CWE-470",
    "go-regex-injection": "CWE-1333",
    "go-regexp-compile-loop": "CWE-1078",
    "go-select-default-spin": "CWE-1078",
    "go-sql-join": "CWE-89",
    "go-swallowed-error": "CWE-390",
    "go-template-html-unescaped": "CWE-79",
    "go-template-js-func": "CWE-79",
    "go-test-fatal-goroutine": "CWE-617",
    "go-waitgroup-add-inside": "CWE-362",
    "go-weak-crypto-rc4": "CWE-327",
    "go-weak-random": "CWE-330",
    "go-append-prealloc": "CWE-1078",
    "go-bare-return-error": "CWE-252",
    "go-bind-all-interfaces": "CWE-668",
    "go-bool-param": "CWE-1078",
    "go-cgo-usage": "CWE-676",
    "go-channel-deadlock": "CWE-833",
    "go-context-todo": "CWE-1078",
    "go-defer-in-hot-path": "CWE-1078",
    "go-defer-os-exit": "CWE-404",
    "go-empty-interface": "CWE-1078",
    "go-error-type-assert": "CWE-253",
    "go-errors-new-fmt": "CWE-1078",
    "go-exported-no-doc": "CWE-1078",
    "go-file-not-closed": "CWE-404",
    "go-float-equality": "CWE-480",
    "go-fmt-sprintf-concat": "CWE-1078",
    "go-getter-prefix": "CWE-1078",
    "go-hardcoded-ip": "CWE-547",
    "go-init-function": "CWE-1078",
    "go-integer-overflow": "CWE-190",
    "go-ioutil-deprecated": "CWE-1078",
    "go-json-marshal-loop": "CWE-1078",
    "go-json-number-overflow": "CWE-190",
    "go-large-struct-value": "CWE-1078",
    "go-log-injection": "CWE-117",
    "go-magic-number": "CWE-1078",
    "go-map-prealloc": "CWE-1078",
    "go-naked-return": "CWE-1078",
    "go-nil-interface-method": "CWE-476",
    "go-nil-slice-append": "CWE-1078",
    "go-no-csrf": "CWE-352",
    "go-once-reset": "CWE-362",
    "go-recover-all": "CWE-396",
    "go-rows-not-closed": "CWE-404",
    "go-string-contains-loop": "CWE-1078",
    "go-string-index-rune": "CWE-1078",
    "go-stuttering-name": "CWE-1078",
    "go-sync-pool-new": "CWE-1078",
    "go-test-parallel-shared": "CWE-362",
    "go-ticker-not-stopped": "CWE-404",
    "go-time-equal": "CWE-1078",
    "go-time-now-loop": "CWE-1078",
    "go-todo-fixme": "CWE-546",
    "go-underscore-name": "CWE-1078",
    "go-unsafe-sizeof": "CWE-676",
    "go-unvalidated-redirect-url": "CWE-601",
    "go-xml-external-entity": "CWE-611",
    "go-zip-slip": "CWE-22",
    # ── Express / Node.js expansion ────────────────────────────────────
    "express-session-no-httponly": "CWE-1004",
    "express-session-no-secure": "CWE-614",
    # ── Next.js expansion ──────────────────────────────────────────────
    "nextjs-api-no-auth": "CWE-862",
    # ── Python XXE / XML ───────────────────────────────────────────────
    "lxml-parse-untrusted": "CWE-611",
    "xml-sax-parser": "CWE-611",
    "elementtree-defused": "CWE-611",
    "xml-parse-untrusted": "CWE-611",
    # ── Prompt Injection (LLM Security) ──────────────────────────────
    # Direct injection — user input interpolated into prompts (CWE-74: Injection)
    "prompt-injection-fstring": "CWE-74",
    "prompt-injection-format": "CWE-74",
    "prompt-injection-concat": "CWE-74",
    "prompt-injection-percent": "CWE-74",
    "prompt-injection-template-literal": "CWE-74",
    "prompt-injection-system-role-fstring": "CWE-74",
    "prompt-injection-system-role-template": "CWE-74",
    "prompt-injection-system-content-js": "CWE-74",
    "prompt-injection-system-content-concat": "CWE-74",
    "prompt-injection-system-content-ts": "CWE-74",
    # SDK-specific direct injection
    "prompt-injection-openai-fstring": "CWE-74",
    "prompt-injection-openai-format": "CWE-74",
    "prompt-injection-openai-template": "CWE-74",
    "prompt-injection-openai-concat": "CWE-74",
    "prompt-injection-openai-ts": "CWE-74",
    "prompt-injection-anthropic-fstring": "CWE-74",
    "prompt-injection-anthropic-js": "CWE-74",
    "prompt-injection-anthropic-ts": "CWE-74",
    "prompt-injection-langchain-fstring": "CWE-74",
    "prompt-injection-langchain-system-var": "CWE-74",
    "prompt-injection-langchain-js": "CWE-74",
    "prompt-injection-langchain-ts": "CWE-74",
    "prompt-injection-litellm": "CWE-74",
    "prompt-injection-genai": "CWE-74",
    "prompt-injection-cohere": "CWE-74",
    "prompt-injection-llamaindex-fstring": "CWE-74",
    "prompt-injection-jinja-prompt": "CWE-94",
    "prompt-injection-vercel-ai": "CWE-74",
    "prompt-injection-vercel-ai-ts": "CWE-74",
    # Java/Go SDK-specific
    "prompt-injection-java-format": "CWE-74",
    "prompt-injection-java-concat": "CWE-74",
    "prompt-injection-java-stringbuilder": "CWE-74",
    "prompt-injection-spring-ai": "CWE-74",
    "prompt-injection-system-msg-java": "CWE-74",
    "prompt-injection-go-sprintf": "CWE-74",
    "prompt-injection-go-concat": "CWE-74",
    "prompt-injection-go-builder": "CWE-74",
    # Indirect injection — untrusted external content in prompts (CWE-94: Code Injection)
    "prompt-injection-url-to-prompt": "CWE-94",
    "prompt-injection-file-to-prompt": "CWE-94",
    "prompt-injection-db-to-prompt": "CWE-94",
    "prompt-injection-email-to-prompt": "CWE-94",
    "prompt-injection-scrape-to-prompt": "CWE-94",
    # Input validation before LLM calls (CWE-20: Improper Input Validation)
    "prompt-injection-request-to-llm": "CWE-20",
    "prompt-injection-request-to-llm-js": "CWE-20",
    # Insecure output handling — LLM output to dangerous sinks
    "llm-output-to-exec": "CWE-94",
    "llm-output-to-sql": "CWE-89",
    "llm-output-to-eval-js": "CWE-94",
    "llm-output-to-eval-ts": "CWE-94",
    "llm-output-to-innerhtml": "CWE-79",
    "llm-output-to-sql-js": "CWE-89",
    "llm-output-to-exec-java": "CWE-94",
    "llm-output-to-exec-go": "CWE-94",
    # LLM safety & configuration
    "llm-safety-disabled-google": "CWE-693",
    "llm-safety-disabled-cohere": "CWE-693",
    "llm-safety-disabled-mistral": "CWE-693",
    "llm-temperature-max": "CWE-693",
    # llm-no-max-tokens removed (regex can't handle nested parens)
    # Multi-turn / conversation injection
    "llm-client-controlled-messages": "CWE-20",
    "llm-client-messages-direct": "CWE-20",
    "llm-role-from-user-input": "CWE-74",
    # Secrets in prompts
    "llm-secret-in-prompt": "CWE-200",
    "llm-connection-string-in-prompt": "CWE-200",
    # Dangerous executors
    "llm-langchain-python-repl": "CWE-94",
    "llm-langchain-bash": "CWE-78",
    "llm-agent-unbounded-loop": "CWE-400",
    # Namespace leakage
    "prompt-injection-format-locals": "CWE-200",
    "prompt-injection-format-map-locals": "CWE-200",
    # Additional output handling
    "llm-output-to-file": "CWE-22",
    "llm-output-to-html": "CWE-79",
    "llm-output-to-import": "CWE-94",
    "llm-output-to-pickle": "CWE-502",
    "llm-output-to-redirect": "CWE-601",
    "llm-output-to-fs": "CWE-22",
    # Safety checks
    "llm-no-refusal-check": "CWE-252",
    # RAG & MCP
    "llm-rag-unsanitized-ingest": "CWE-94",
    "llm-mcp-tool-shell": "CWE-78",
    "llm-mcp-tool-file-delete": "CWE-250",
    "llm-mcp-tool-exec-js": "CWE-78",
    # Content-field-level injection
    "prompt-injection-content-fstring": "CWE-74",
    "prompt-injection-content-template": "CWE-74",
    # Anthropic SDK variants
    "prompt-injection-anthropic-format": "CWE-74",
    "prompt-injection-anthropic-concat": "CWE-74",
    # Tool call argument injection
    "llm-tool-call-to-exec": "CWE-94",
    "llm-tool-call-to-sql": "CWE-89",
    # Supply chain (OWASP LLM03)
    "llm-untrusted-model-load": "CWE-494",
    "llm-model-download-url": "CWE-494",
    # Excessive agency (OWASP LLM06)
    "llm-auto-approve-tools": "CWE-693",
    "llm-agent-unrestricted-tools": "CWE-250",
    # System prompt leakage (OWASP LLM07)
    "llm-system-prompt-logged": "CWE-200",
    "llm-system-prompt-returned": "CWE-200",
    # Additional SDK coverage
    "prompt-injection-ollama": "CWE-74",
    "prompt-injection-bedrock": "CWE-74",
    "prompt-injection-groq": "CWE-74",
    # Multimodal injection
    "llm-untrusted-image-to-vision": "CWE-74",
    "llm-base64-image-from-input": "CWE-74",
    # Sensitive info in responses (OWASP LLM02)
    "llm-response-no-pii-filter": "CWE-200",
    "llm-training-data-leak-check": "CWE-200",
}


# NIST SP 800-53 control mappings
# Maps rule names to relevant NIST controls
NIST_MAP: dict[str, list[str]] = {
    # Secrets / credentials
    "hardcoded-secret": ["SC-12", "SC-28", "IA-5"],
    "aws-credentials": ["SC-12", "SC-28", "IA-5"],
    "private-key": ["SC-12", "SC-28", "IA-5"],
    "db-connection-string": ["SC-12", "SC-28", "IA-5"],
    # Injection
    "sql-injection-execute": ["SI-10", "SI-16"],
    "sql-injection-format": ["SI-10", "SI-16"],
    "sql-injection-fstring": ["SI-10", "SI-16"],
    "sql-injection-concat": ["SI-10", "SI-16"],
    "sql-injection-percent": ["SI-10", "SI-16"],
    "sql-injection-raw": ["SI-10", "SI-16"],
    "eval-usage": ["SI-10", "SI-16"],
    "exec-usage": ["SI-10", "SI-16"],
    "os-system": ["SI-10", "SI-16"],
    "shell-true": ["SI-10", "SI-16"],
    "subprocess-audit": ["SI-10", "SI-16"],
    "taint-flow": ["SI-10", "SI-16"],
    "taint-flow-cross-file": ["SI-10", "SI-16"],
    # XSS
    "innerhtml": ["SI-10", "SI-16"],
    "insert-adjacent-html": ["SI-10", "SI-16"],
    "document-write": ["SI-10", "SI-16"],
    # Deserialization
    "pickle-unsafe": ["SI-10", "SI-16"],
    "yaml-unsafe": ["SI-10", "SI-16"],
    "unsafe-deserialization": ["SI-10", "SI-16"],
    # SSRF
    "ssrf-risk": ["SI-10", "SC-7"],
    "url-scheme-audit": ["SI-10", "SC-7"],
    # SSTI
    "ssti-risk": ["SI-10", "SI-16"],
    # XXE
    "xxe-risk": ["SI-10", "SC-4"],
    # JWT
    "jwt-insecure": ["SC-13", "IA-5"],
    # Hardcoded config
    "hardcoded-ip": ["CM-6"],
    # Tempfile
    "insecure-tempfile": ["SC-28"],
    # Fold 2 additions
    "os-popen": ["SI-10", "SI-16"],
    "subprocess-shell": ["SI-10", "SI-16"],
    "os-startfile": ["SI-10", "SI-16"],
    "insecure-file-permissions": ["AC-3", "AC-6"],
    "bind-all-interfaces": ["SC-7", "CM-6"],
    "jinja2-autoescape-off": ["SI-10", "SI-16"],
    "pycrypto-deprecated": ["SC-13", "SC-12"],
    "ssl-wrap-socket": ["SC-8", "SC-13"],
    "requests-no-verify": ["SC-8", "SC-13"],
    "ssl-verify-disabled": ["SC-8", "SC-13"],
    "hardcoded-tmp": ["SC-28"],
    "hardcoded-password-default": ["SC-12", "IA-5"],
    "debug-enabled": ["CM-6", "SI-11"],
    "toctou-file-check": ["SI-16"],
    "archive-slip": ["SI-10", "AC-3"],
    "tarfile-open": ["SI-10", "AC-3"],
    "unencrypted-ftp": ["SC-8", "SC-13"],
    "unencrypted-telnet": ["SC-8", "SC-13"],
    "smtp-cleartext": ["SC-8", "SC-13"],
    "webbrowser-open": ["SI-10"],
    "ctypes-load-library": ["SI-10", "SI-16"],
    "rmtree-audit": ["SI-10", "AC-3"],
    "dynamic-import": ["SI-10", "SI-16"],
    "env-path-injection": ["CM-6", "SI-16"],
    "sys-path-modify": ["CM-6", "SI-16"],
    "compile-usage": ["SI-10", "SI-16"],
    "regex-injection": ["SI-10"],
    # Python OWASP expansion
    "hardcoded-secret-key": ["SC-12", "SC-28", "IA-5"],
    "csrf-middleware-disabled": ["SI-10", "SC-23"],
    "csrf-exempt": ["SI-10", "SC-23"],
    "django-allowed-hosts-wildcard": ["CM-6", "SC-7"],
    "django-raw-sql": ["SI-10", "SI-16"],
    "unsafe-redirect": ["SI-10", "SC-7"],
    "flask-send-file-traversal": ["SI-10", "AC-3"],
    "weak-tls-version": ["SC-8", "SC-13"],
    "weak-cipher-suite": ["SC-8", "SC-13"],
    "empty-password-check": ["IA-5", "IA-6"],
    "empty-password-connection": ["IA-5", "IA-6"],
    "cors-wildcard": ["SC-7", "AC-4"],
    "security-header-disabled": ["SC-8", "CM-6"],
    "ssl-redirect-disabled": ["SC-8", "SC-13"],
    "zipfile-extract-audit": ["SI-10", "AC-3"],
    "session-cookie-insecure": ["SC-8", "SC-23"],
    "session-cookie-no-httponly": ["SC-23", "SI-10"],
    "http-connection-cleartext": ["SC-8", "SC-13"],
    "os-exec": ["SI-10", "SI-16"],
    "os-spawn": ["SI-10", "SI-16"],
    # Cryptography
    "weak-hash": ["SC-13", "SC-12"],
    "weak-random": ["SC-13", "SC-12"],
    "insecure-crypto": ["SC-13", "SC-12"],
    "insecure-ecb-mode": ["SC-13", "SC-12"],
    "weak-rsa-key": ["SC-13", "SC-12"],
    "insecure-http": ["SC-8", "SC-13"],
    "requests-no-timeout": ["SC-5", "SI-17"],
    "logging-config-listen": ["SI-10", "CM-7"],
    "django-mark-safe": ["SI-10"],
    "django-extra-sql": ["SI-10"],
    "paramiko-auto-add-policy": ["SC-8", "SC-23"],
    "paramiko-exec-command": ["SI-10", "SI-16"],
    # Path traversal
    "path-traversal": ["SI-10", "AC-3"],
    # Logging
    "logging-sensitive-data": ["AU-3", "SI-11"],
    "console-log": ["AU-3"],
    "fmt-print": ["AU-3"],
    # Error handling
    "bare-except": ["SI-11"],
    "exception-swallowed": ["SI-11"],
    "empty-exception-handler": ["SI-11"],
    "unchecked-error": ["SI-11"],
    "unwrap": ["SI-11"],
    "expect-panic": ["SI-11"],
    # Resource management
    "open-without-with": ["SC-24"],
    "resource-leak": ["SC-24"],
    "null-dereference": ["SI-16"],
    # Code quality (mapped to SA family — System and Services Acquisition)
    "high-complexity": ["SA-11"],
    "too-many-args": ["SA-11"],
    "god-class": ["SA-11"],
    "long-method": ["SA-11"],
    "near-duplicate": ["SA-11"],
    "semantic-clone": ["SA-11"],
    "dead-function": ["SA-11"],
    "unreachable-code": ["SA-11"],
    "unused-import": ["SA-11"],
    "unused-variable": ["SA-11"],
    # SCA
    "vulnerable-dependency": ["RA-5", "SI-2"],
    # JavaScript/TypeScript expansion
    "function-constructor": ["SI-10", "SI-16"],
    "outerhtml": ["SI-10", "SI-16"],
    "proto-access": ["SI-10", "SI-16"],
    "object-assign-merge": ["SI-10", "SI-16"],
    "open-redirect": ["SI-10", "SC-7"],
    "insecure-random": ["SC-13", "SC-12"],
    "postmessage-no-origin": ["SI-10", "SC-7"],
    "insecure-cookie": ["SC-8", "SC-23"],
    "jwt-alg-none": ["SC-13", "IA-5"],
    "nosql-injection": ["SI-10", "SI-16"],
    "js-command-injection": ["SI-10", "SI-16"],
    "js-command-injection-template": ["SI-10", "SI-16"],
    "js-path-traversal": ["SI-10", "AC-3"],
    "js-hardcoded-jwt-secret": ["SC-12", "SC-28", "IA-5"],
    "js-tls-reject-unauthorized": ["SC-8", "SC-13"],
    "js-tls-env-disable": ["SC-8", "SC-13"],
    "debugger-statement": ["CM-6", "SI-11"],
    "delete-array": ["SA-11"],
    "empty-catch": ["SI-11"],
    "alert-usage": ["CM-6"],
    "missing-await-hint": ["SI-11"],
    "promise-no-catch": ["SI-11"],
    "settimeout-string": ["SI-10", "SI-16"],
    "prototype-overwrite": ["SA-11"],
    "with-statement": ["SA-11"],
    "bitwise-in-condition": ["SA-11"],
    "void-zero": ["SA-11"],
    # Go expansion
    "go-sql-sprintf": ["SI-10", "SI-16"],
    "go-sql-concat": ["SI-10", "SI-16"],
    "go-command-injection": ["SI-10", "SI-16"],
    "go-command-injection-ctx": ["SI-10", "SI-16"],
    "go-path-traversal": ["SI-10", "AC-3"],
    "go-hardcoded-credential": ["SC-12", "SC-28", "IA-5"],
    "go-weak-crypto-md5": ["SC-13", "SC-12"],
    "go-weak-crypto-sha1": ["SC-13", "SC-12"],
    "go-weak-crypto-des": ["SC-13", "SC-12"],
    "go-insecure-tls": ["SC-8", "SC-13"],
    "go-weak-tls-version": ["SC-8", "SC-13"],
    "go-unsafe-pointer": ["SA-11"],
    "go-ssrf": ["SI-10", "SC-7"],
    "go-open-redirect": ["SI-10", "SC-7"],
    "go-defer-in-loop": ["SA-11"],
    "go-goroutine-anonymous": ["SA-11"],
    "go-nil-map": ["SI-16"],
    "go-panic": ["SI-11"],
    "go-string-byte-copy": ["SA-11"],
    "go-global-var": ["SA-11"],
    # Java-specific rules
    "java-sql-injection": ["SI-10", "SI-16"],
    "java-xss": ["SI-10", "SI-16"],
    "java-cmdi": ["SI-10", "SI-16"],
    "java-ldap-injection": ["SI-10", "SI-16"],
    "java-xpath-injection": ["SI-10", "SI-16"],
    "java-weak-crypto": ["SC-13", "SC-12"],
    "java-weak-hash": ["SC-13", "SC-12"],
    "java-weak-random": ["SC-13", "SC-12"],
    "java-trust-boundary": ["SI-10", "AC-4"],
    "java-insecure-cookie": ["SC-8", "SC-23"],
    "java-path-traversal": ["SI-10", "AC-3"],
    # Java — Spring Security
    "java-spring-csrf-disabled": ["SI-10", "SC-23"],
    "java-spring-permit-all-sensitive": ["AC-3", "AC-6"],
    "java-spring-missing-preauthorize": ["AC-3", "AC-6"],
    "java-spring-cors-allow-all": ["SC-7", "AC-4"],
    "java-spring-weak-password-encoder": ["IA-5", "SC-13"],
    "java-spring-security-debug": ["CM-6", "SI-11"],
    "java-spring-permit-all-wildcard": ["AC-3", "AC-6"],
    # Java — Spring MVC
    "java-spring-open-redirect": ["SI-10", "SC-7"],
    "java-spring-missing-valid": ["SI-10"],
    "java-spring-unvalidated-forward": ["SI-10", "AC-3"],
    "java-spring-path-variable-traversal": ["SI-10", "AC-3"],
    # Java — Deserialization
    "java-unsafe-deserialization": ["SI-10", "SI-16"],
    "java-xmldecoder-deserialization": ["SI-10", "SI-16"],
    "java-snakeyaml-unsafe": ["SI-10", "SI-16"],
    "java-kryo-unsafe": ["SI-10", "SI-16"],
    "java-xstream-unsafe": ["SI-10", "SI-16"],
    # Java — XXE
    "java-xxe-documentbuilder": ["SI-10", "SC-4"],
    "java-xxe-saxparser": ["SI-10", "SC-4"],
    "java-xxe-xmlreader": ["SI-10", "SC-4"],
    "java-xxe-transformer": ["SI-10", "SC-4"],
    # Java — SSRF
    "java-ssrf-url": ["SI-10", "SC-7"],
    "java-ssrf-httpclient": ["SI-10", "SC-7"],
    "java-ssrf-resttemplate": ["SI-10", "SC-7"],
    "java-ssrf-webclient": ["SI-10", "SC-7"],
    # Java — Cryptography
    "java-ecb-mode": ["SC-13", "SC-12"],
    "java-static-iv": ["SC-13", "SC-12"],
    "java-weak-key-size": ["SC-13", "SC-12"],
    "java-insecure-pbe": ["SC-13", "SC-12"],
    "java-md5-sha1-password": ["IA-5", "SC-13"],
    "java-null-cipher": ["SC-13", "SC-12"],
    "java-static-encryption-key": ["SC-12", "SC-28"],
    "java-weak-tls": ["SC-8", "SC-13"],
    # Java — File Upload
    "java-unrestricted-upload": ["SI-10", "SC-18"],
    "java-upload-original-filename": ["SI-10", "AC-3"],
    "java-upload-no-size-limit": ["SC-5", "SI-10"],
    # Java — JNDI
    "java-jndi-injection": ["SI-10", "SI-16"],
    "java-jndi-lookup-concat": ["SI-10", "SI-16"],
    "java-jndi-ldap-rmi": ["SI-10", "SI-16"],
    "java-jndi-lookup-variable": ["SI-10", "SI-16"],
    # Java — Expression Language
    "java-spel-injection": ["SI-10", "SI-16"],
    "java-spel-injection-concat": ["SI-10", "SI-16"],
    "java-el-injection": ["SI-10", "SI-16"],
    "java-spel-value-annotation": ["SI-10", "SI-16"],
    "java-spel-parse-variable": ["SI-10", "SI-16"],
    # Java — Logging
    "java-log-injection": ["AU-9", "SI-10"],
    "java-log4j-lookup": ["SI-10", "SI-16"],
    "java-log-format-string": ["AU-9", "SI-10"],
    # Java — Authentication
    "java-hardcoded-password": ["IA-5", "SC-28"],
    "java-empty-password": ["IA-5"],
    "java-default-credentials": ["IA-5", "SC-28"],
    "java-trust-all-certs": ["SC-8", "SC-13", "IA-5"],
    "java-hostname-verifier-bypass": ["SC-8", "SC-13"],
    # Java — JWT
    "java-jwt-none-algorithm": ["SC-13", "IA-5"],
    "java-jwt-missing-expiration": ["AC-12", "SC-23"],
    "java-jwt-weak-secret": ["SC-12", "SC-13"],
    "java-jwt-no-verification": ["SC-13", "IA-5"],
    # Java — Hibernate/HQL
    "java-hql-injection": ["SI-10", "SI-16"],
    "java-hql-injection-var": ["SI-10", "SI-16"],
    "java-native-query-injection": ["SI-10", "SI-16"],
    # Java — XML
    "java-xstream-no-allowlist": ["SI-10", "SI-16"],
    "java-dom-parse-no-limits": ["SC-5", "SI-10"],
    "java-jaxb-external-entity": ["SI-10", "SC-4"],
    # Java — Error Handling
    "java-stacktrace-exposure": ["SI-11"],
    "java-verbose-error-response": ["SI-11"],
    "java-catch-generic-exception": ["SI-11"],
    "java-empty-catch-block": ["SI-11"],
    "java-printstacktrace": ["SI-11"],
    # Java — Concurrency
    "java-double-checked-locking": ["SA-11"],
    "java-non-atomic-check-then-act": ["SA-11"],
    "java-toctou-file-check-then-act": ["SA-11"],
    "java-async-file-operation": ["SA-11"],
    "java-synchronized-on-boxed": ["SA-11"],
    # Java — Android
    "java-android-exported-component": ["AC-3", "AC-6"],
    "java-android-webview-js": ["SI-10", "SC-18"],
    "java-android-cleartext-traffic": ["SC-8"],
    "java-android-webview-file-access": ["AC-3", "AC-6"],
    "java-android-world-readable": ["AC-3", "AC-6"],
    # Java — Kotlin Interop
    "java-kotlin-platform-type": ["SA-11"],
    "java-nullable-annotation-missing": ["SA-11"],
    # Java — Additional
    "java-template-injection": ["SI-10", "SI-16"],
    "java-regex-dos": ["SC-5", "SI-10"],
    "java-unvalidated-redirect-response": ["SI-10", "SC-7"],
    "java-header-injection": ["SI-10", "SI-16"],
    "java-insecure-ssl-factory": ["SC-8", "SC-13"],
    "java-system-exit": ["SA-11"],
    "java-thread-sleep-in-sync": ["SA-11"],
    "java-unsafe-reflection": ["SI-10", "SI-16"],
    "java-insecure-temp-file": ["AC-3", "AC-6"],
    "java-runtime-exec": ["SI-10", "SI-16"],
    "java-cors-credentials-wildcard": ["SC-7", "AC-4"],
    "java-spring-actuator-exposed": ["CM-6", "AC-3"],
    "java-deserialization-gadget": ["SI-10", "SI-16"],
    "java-insecure-xml-validation": ["SI-10", "SC-4"],
    "java-permission-check-missing": ["AC-3", "AC-6"],
    "java-unsafe-object-binding": ["SI-10", "AC-3"],
    # ── Cross-language: Credentials & Secrets ──────────────────────────
    "boto3-hardcoded-key": ["SC-12", "SC-28", "IA-5"],
    "flask-secret-hardcoded": ["SC-12", "SC-28", "IA-5"],
    "generic-bearer-token": ["SC-12", "SC-28", "IA-5"],
    "github-token": ["SC-12", "SC-28", "IA-5"],
    "go-static-key": ["SC-12", "SC-28", "IA-5"],
    "google-api-key": ["SC-12", "SC-28", "IA-5"],
    "hardcoded-api-key": ["SC-12", "SC-28", "IA-5"],
    "hardcoded-credential": ["SC-12", "SC-28", "IA-5"],
    "hardcoded-jwt-secret": ["SC-12", "SC-28", "IA-5"],
    "hardcoded-password": ["SC-12", "SC-28", "IA-5"],
    "hardcoded-secret-dict": ["SC-12", "SC-28", "IA-5"],
    "lambda-env-secret": ["SC-12", "SC-28", "IA-5"],
    "npm-token": ["SC-12", "SC-28", "IA-5"],
    "sendgrid-key": ["SC-12", "SC-28", "IA-5"],
    "slack-token": ["SC-12", "SC-28", "IA-5"],
    "stripe-key": ["SC-12", "SC-28", "IA-5"],
    "twilio-key": ["SC-12", "SC-28", "IA-5"],
    "base64-secret": ["SC-12", "SC-28", "IA-5"],
    "process-env-default-secret": ["SC-12", "SC-28", "IA-5"],
    "env-file-committed": ["SC-12", "SC-28", "IA-5"],
    "env-var-secret": ["SC-12", "SC-28", "IA-5"],
    "password-in-query-string": ["SC-12", "SC-28", "IA-5"],
    "password-in-url": ["SC-12", "SC-28", "IA-5"],
    # ── Cross-language: SQL Injection ──────────────────────────────────
    "format-string-sql": ["SI-10", "SI-16"],
    "knex-raw-interpolation": ["SI-10", "SI-16"],
    "sequelize-raw-query": ["SI-10", "SI-16"],
    "sql-string-concat": ["SI-10", "SI-16"],
    "sql-template-literal": ["SI-10", "SI-16"],
    "sqlalchemy-execute-concat": ["SI-10", "SI-16"],
    "sqlalchemy-execute-format": ["SI-10", "SI-16"],
    "sqlalchemy-execute-fstring": ["SI-10", "SI-16"],
    "sqlalchemy-text-format": ["SI-10", "SI-16"],
    # ── Cross-language: Command Injection ──────────────────────────────
    "command-shell": ["SI-10", "SI-16"],
    "shell-injection": ["SI-10", "SI-16"],
    "command-injection": ["SI-10", "SI-16"],
    "subprocess-popen-concat": ["SI-10", "SI-16"],
    "subprocess-shell-user-input": ["SI-10", "SI-16"],
    "async-subprocess-shell": ["SI-10", "SI-16"],
    "child-process-spawn-shell": ["SI-10", "SI-16"],
    # ── Cross-language: Deserialization ────────────────────────────────
    "deserialization-unsafe": ["SI-10", "SI-16"],
    "dill-loads-unsafe": ["SI-10", "SI-16"],
    "js-yaml-unsafe-load": ["SI-10", "SI-16"],
    "marshal-loads-unsafe": ["SI-10", "SI-16"],
    "node-serialize-usage": ["SI-10", "SI-16"],
    "pickle-from-request": ["SI-10", "SI-16"],
    "serialize-unserialize": ["SI-10", "SI-16"],
    "shelve-open-unsafe": ["SI-10", "SI-16"],
    "dunder-import-dynamic": ["SI-10", "SI-16"],
    "multiprocessing-pickle": ["SI-10", "SI-16"],
    "pydantic-arbitrary-types": ["SI-10", "SI-16"],
    # ── Cross-language: XSS ───────────────────────────────────────────
    "react-dangerously-set-innerhtml": ["SI-10", "SI-16"],
    "react-href-javascript": ["SI-10", "SI-16"],
    "react-ref-innerhtml": ["SI-10", "SI-16"],
    "raw-html-response": ["SI-10", "SI-16"],
    "xss-document-write": ["SI-10", "SI-16"],
    "xss-innerhtml": ["SI-10", "SI-16"],
    # ── Cross-language: SSRF ──────────────────────────────────────────
    "ssrf-axios-user-url": ["SI-10", "SC-7"],
    "ssrf-fetch-user-url": ["SI-10", "SC-7"],
    "ssrf-got-user-url": ["SI-10", "SC-7"],
    "ssrf-request-user-url": ["SI-10", "SC-7"],
    # ── Cross-language: Path Traversal ────────────────────────────────
    "fs-user-controlled-read": ["SI-10", "AC-3"],
    "fs-user-controlled-unlink": ["SI-10", "AC-3"],
    "fs-user-controlled-write": ["SI-10", "AC-3"],
    "zip-slip-extract": ["SI-10", "AC-3"],
    "file-open-fstring": ["SI-10", "AC-3"],
    # ── Cross-language: Cryptography ──────────────────────────────────
    "crypto-create-cipher": ["SC-13", "SC-12"],
    "crypto-des-algorithm": ["SC-13", "SC-12"],
    "crypto-ecb-mode": ["SC-13", "SC-12"],
    "crypto-ecb-aes-new": ["SC-13", "SC-12"],
    "crypto-ecb-java": ["SC-13", "SC-12"],
    "insecure-blowfish": ["SC-13", "SC-12"],
    "insecure-des": ["SC-13", "SC-12"],
    "insecure-rc4": ["SC-13", "SC-12"],
    "crypto-weak-random-token": ["SC-13", "SC-12"],
    "crypto-md5-hmac": ["SC-13", "SC-12"],
    "crypto-weak-hash-md5": ["SC-13", "SC-12"],
    "crypto-weak-hash-sha1": ["SC-13", "SC-12"],
    "weak-crypto-md5": ["SC-13", "SC-12"],
    "weak-crypto-sha1": ["SC-13", "SC-12"],
    "weak-hash-md5": ["SC-13", "SC-12"],
    "weak-hash-sha1": ["SC-13", "SC-12"],
    "hashlib-new-weak": ["SC-13", "SC-12"],
    "crypto-static-iv": ["SC-13", "SC-12"],
    "crypto-weak-pbkdf2": ["SC-13", "SC-12"],
    "bcrypt-low-rounds": ["SC-13", "SC-12"],
    "weak-bcrypt-rounds": ["SC-13", "SC-12"],
    # ── Cross-language: TLS/SSL ───────────────────────────────────────
    "insecure-ssl-context": ["SC-8", "SC-13"],
    "tls-no-verify": ["SC-8", "SC-13"],
    "aiohttp-no-verify": ["SC-8", "SC-13"],
    "urllib3-no-verify": ["SC-8", "SC-13"],
    "ssl-no-hostname-check": ["SC-8", "SC-13"],
    # ── Cross-language: CORS ──────────────────────────────────────────
    "cors-reflect-origin": ["SC-7", "AC-4"],
    "express-cors-credentials-wildcard": ["SC-7", "AC-4"],
    "fastapi-cors-wildcard": ["SC-7", "AC-4"],
    "fastapi-credentials-wildcard": ["SC-7", "AC-4"],
    # ── Cross-language: CSRF ──────────────────────────────────────────
    "csrf-disabled": ["SI-10", "SC-23"],
    # ── Cross-language: Open Redirect ─────────────────────────────────
    "window-open-user-url": ["SI-10", "SC-7"],
    # ── Cross-language: Prototype Pollution ────────────────────────────
    "deep-merge-no-proto-check": ["SI-10", "SI-16"],
    "lodash-merge-user-input": ["SI-10", "SI-16"],
    "object-assign-user-input": ["SI-10", "SI-16"],
    "spread-constructor-pollution": ["SI-10", "SI-16"],
    "prototype-pollution-merge": ["SI-10", "SI-16"],
    # ── Cross-language: LDAP / XPath Injection ────────────────────────
    "ldap-injection": ["SI-10", "SI-16"],
    "xpath-injection": ["SI-10", "SI-16"],
    # ── Cross-language: JWT ───────────────────────────────────────────
    "jwt-none-algorithm": ["SC-13", "IA-5"],
    "jwt-no-expiry": ["AC-12", "SC-23"],
    # ── Cross-language: Header Injection ──────────────────────────────
    "header-injection": ["SI-10", "SI-16"],
    # ── Cross-language: NoSQL Injection ────────────────────────────────
    "mongodb-regex-user-input": ["SI-10", "SI-16"],
    "mongodb-where-operator": ["SI-10", "SI-16"],
    "mongoose-find-user-object": ["SI-10", "SI-16"],
    "nosql-injection-mongodb": ["SI-10", "SI-16"],
    # ── Cross-language: Information Disclosure ─────────────────────────
    "nextjs-exposed-server-env": ["CM-6", "SI-11"],
    "nextjs-getserversideprops-leak": ["CM-6", "SI-11"],
    "nuxt-exposed-runtime-secret": ["CM-6", "SI-11"],
    "information-disclosure-stacktrace": ["CM-6", "SI-11"],
    "graphql-introspection-enabled": ["CM-6", "SI-11"],
    "source-map-in-production": ["CM-6", "SI-11"],
    "directory-listing": ["CM-6", "SI-11"],
    # ── Cross-language: Debug Left In Code ─────────────────────────────
    "code-interactive-console": ["CM-6", "SI-11"],
    "werkzeug-debugger": ["CM-6", "SI-11"],
    "dbg-macro": ["CM-6", "SI-11"],
    "flask-debug-production": ["CM-6", "SI-11"],
    "fastapi-debug-docs": ["CM-6", "SI-11"],
    # ── Cross-language: Logging Sensitive Data ─────────────────────────
    "log-credit-card": ["AU-3", "SI-11"],
    "log-password-interpolation": ["AU-3", "SI-11"],
    "println-in-lib": ["AU-3", "SI-11"],
    # ── Cross-language: Timing Attack ──────────────────────────────────
    "timing-attack-comparison": ["SC-13", "SI-10"],
    # ── Cross-language: Mass Assignment ────────────────────────────────
    "mass-assignment": ["SI-10", "AC-3"],
    "class-manipulation": ["SI-10", "AC-3"],
    "setattr-dynamic": ["SI-10", "AC-3"],
    # ── Cross-language: ReDoS ──────────────────────────────────────────
    "re-dos-quantifier": ["SC-5", "SI-10"],
    "redos-nested-quantifier": ["SC-5", "SI-10"],
    "regex-dos": ["SC-5", "SI-10"],
    "redos-overlapping-alternation": ["SC-5", "SI-10"],
    # ── Cross-language: File Upload ────────────────────────────────────
    "unvalidated-file-upload": ["SI-10", "SC-18"],
    "file-upload-unrestricted": ["SI-10", "SC-18"],
    # ── Cross-language: File Permissions ───────────────────────────────
    "file-world-writable": ["AC-3", "AC-6"],
    "fs-chmod-world-writable": ["AC-3", "AC-6"],
    "s3-public-acl": ["AC-3", "AC-6"],
    # ── Cross-language: Resource Management / DoS ──────────────────────
    "forget-leak": ["SC-24"],
    "reqwest-no-timeout": ["SC-5", "SI-10"],
    "graphql-no-depth-limit": ["SC-5", "SI-10"],
    "graphql-no-cost-analysis": ["SC-5", "SI-10"],
    "express-bodyparser-no-limit": ["SC-5", "SI-10"],
    # ── Cross-language: Race Conditions ────────────────────────────────
    "race-condition-mkdir": ["SA-11"],
    "os-link-toctou": ["SA-11"],
    # ── Cross-language: Code Injection / Eval ──────────────────────────
    "getattr-user-input": ["SI-10", "SI-16"],
    "globals-manipulation": ["SI-10", "SI-16"],
    "vm-module-escape": ["SI-10", "SI-16"],
    # ── Cross-language: Session ────────────────────────────────────────
    "session-insecure": ["SC-8", "SC-23"],
    # ── Cross-language: Cleartext Communication ────────────────────────
    "ftp-no-tls": ["SC-8", "SC-13"],
    "python-http-server": ["SC-8", "SC-13"],
    "websocket-unencrypted": ["SC-8", "SC-13"],
    # ── Cross-language: Misc Security ──────────────────────────────────
    "temp-file-predictable": ["SC-28"],
    "file-mkdtemp-ignore": ["SC-28"],
    "tempfile-predictable-name": ["SC-28"],
    "websocket-no-origin-check": ["SI-10", "SC-7"],
    "dns-rebinding-risk": ["SI-10", "SC-7"],
    "express-no-helmet": ["SC-8", "CM-6"],
    "helmet-csp-unsafe-inline": ["SC-8", "CM-6"],
    "express-trust-proxy-true": ["SI-10", "SC-7"],
    "express-static-dotfiles": ["CM-6", "SI-11"],
    "s3-no-encryption": ["SC-28", "SC-13"],
    "subprocess-env-path": ["CM-6", "SI-16"],
    "process-exit": ["SA-11"],
    "blocking-in-async": ["SA-11"],
    "sleep-in-async": ["SA-11"],
    "transmute": ["SA-11"],
    "raw-pointer-deref": ["SA-11"],
    "signal-handler-unsafe": ["SA-11"],
    "buffer-alloc-unsafe": ["SI-16"],
    "buffer-from-number": ["SI-16"],
    # ── Cross-language: Code Quality / Style ───────────────────────────
    "allow-lint": ["SA-11"],
    "fixme-critical": ["SA-11"],
    "todo-unfinished": ["SA-11"],
    "commented-code-block": ["SA-11"],
    "box-string": ["SA-11"],
    "box-vec": ["SA-11"],
    "clone-on-copy": ["SA-11"],
    "magic-number": ["SA-11"],
    "mixed-indentation": ["SA-11"],
    "trailing-whitespace": ["SA-11"],
    "rc-refcell-vec": ["SA-11"],
    "recursive-type-no-box": ["SA-11"],
    "string-push-in-loop": ["SA-11"],
    "lossy-conversion": ["SA-11"],
    "ts-any-security-context": ["SA-11"],
    "ts-double-assertion": ["SA-11"],
    "ts-non-null-assertion-chain": ["SA-11"],
    # ── TypeScript-specific ────────────────────────────────────────────
    "ts-as-any-cast": ["SA-11"],
    "ts-double-cast": ["SA-11"],
    "ts-non-null-assertion": ["SA-11"],
    "ts-angle-bracket-any": ["SA-11"],
    "ts-ignore-comment": ["SA-11"],
    "ts-expect-error-bypass": ["SA-11"],
    "ts-any-param": ["SA-11"],
    "ts-any-return": ["SA-11"],
    "ts-excessive-any-annotation": ["SA-11"],
    "ts-object-type": ["SA-11"],
    "ts-json-parse-assertion": ["SI-10"],
    "ts-record-string-any": ["SA-11"],
    "ts-type-only-import-runtime": ["SI-10"],
    "ts-declare-ambient": ["SA-11"],
    "ts-satisfies-no-validation": ["SI-10"],
    "ts-unvalidated-external-assertion": ["SI-10"],
    "ts-index-signature-any": ["SA-11"],
    "ts-nestjs-no-auth-guard": ["AC-3"],
    "ts-express-any-body": ["SI-10"],
    "ts-unvalidated-dto": ["SI-10"],
    "ts-graphql-any-return": ["SA-11"],
    "ts-prisma-raw-interpolation": ["SI-10"],
    "ts-typeorm-raw-query": ["SI-10"],
    "ts-nextjs-unvalidated-params": ["SI-10"],
    "ts-react-useeffect-external": ["SI-10"],
    "ts-nocheck": ["SA-11"],
    "ts-triple-slash-disable": ["SA-11"],
    "ts-typeof-object-no-null": ["SA-11"],
    "ts-type-predicate-no-narrow": ["SA-11"],
    "ts-as-const-mutable": ["SA-11"],
    "ts-enum-no-default": ["SA-11"],
    "ts-missing-readonly-config": ["SA-11"],
    "ts-overload-any-fallback": ["SA-11"],
    "ts-generic-any-constraint": ["SA-11"],
    "ts-partial-security-type": ["AC-3"],
    # ── Rust-specific ──────────────────────────────────────────────────
    "panic-in-lib": ["SI-11"],
    "unimplemented-macro": ["SI-11"],
    "unreachable-macro": ["SI-11"],
    "index-panic": ["SI-11"],
    "unwrap-or-default": ["SI-11"],
    "mutex-poison": ["SA-11"],
    # ── Electron-specific ──────────────────────────────────────────────
    "electron-allow-running-insecure": ["CM-6", "SI-16"],
    "electron-context-isolation-off": ["CM-6", "SI-16"],
    "electron-node-integration": ["CM-6", "SI-16"],
    "electron-websecurity-off": ["CM-6", "SI-16"],
    "electron-shell-openexternal": ["SI-10", "SI-16"],
    "electron-remote-module": ["CM-6", "SI-16"],
    "npm-postinstall-script": ["CM-6", "SI-16"],
    "npm-preinstall-script": ["CM-6", "SI-16"],
    "npm-dependency-confusion": ["CM-6", "SI-16"],
    # ── Django-specific ────────────────────────────────────────────────
    "django-extra-fstring": ["SI-10", "SI-16"],
    "django-raw-fstring": ["SI-10", "SI-16"],
    "django-rawsql-format": ["SI-10", "SI-16"],
    # ── PHP-specific ───────────────────────────────────────────────────
    "php-assert-string": ["SI-10", "SI-16"],
    "php-command-injection-backtick": ["SI-10", "SI-16"],
    "php-command-injection-exec": ["SI-10", "SI-16"],
    "php-command-injection-passthru": ["SI-10", "SI-16"],
    "php-command-injection-shell-exec": ["SI-10", "SI-16"],
    "php-command-injection-system": ["SI-10", "SI-16"],
    "php-command-injection-popen": ["SI-10", "SI-16"],
    "php-command-injection-proc-open": ["SI-10", "SI-16"],
    "php-create-function": ["SI-10", "SI-16"],
    "php-curl-ssl-host-off": ["SC-8", "SC-13"],
    "php-curl-ssl-verify-off": ["SC-8", "SC-13"],
    "php-eval": ["SI-10", "SI-16"],
    "php-extract-globals": ["SI-10", "SI-16"],
    "php-file-inclusion-concat": ["SI-10", "SI-16"],
    "php-file-inclusion-variable": ["SI-10", "SI-16"],
    "php-header-injection": ["SI-10", "SI-16"],
    "php-md5-password": ["SC-13", "SC-12"],
    "php-preg-replace-e": ["SI-10", "SI-16"],
    "php-register-globals": ["SI-10", "SI-16"],
    "php-session-fixation": ["SC-23", "AC-12"],
    "php-sha1-password": ["SC-13", "SC-12"],
    "php-sql-injection-interpolation": ["SI-10", "SI-16"],
    "php-sql-injection-mysql": ["SI-10", "SI-16"],
    "php-sql-injection-mysqli-concat": ["SI-10", "SI-16"],
    "php-sql-injection-pdo-concat": ["SI-10", "SI-16"],
    "php-ssrf-file-get-contents": ["SI-10", "SC-7"],
    "php-ssrf-curl": ["SI-10", "SC-7"],
    "php-strcmp-bypass": ["SI-10"],
    "php-type-juggling-password": ["SI-10"],
    "php-unserialize": ["SI-10", "SI-16"],
    "php-deserialize-phar": ["SI-10", "SI-16"],
    "php-weak-encryption": ["SC-13", "SC-12"],
    "php-xss-echo": ["SI-10", "SI-16"],
    "php-xss-no-escape": ["SI-10", "SI-16"],
    "php-error-display": ["CM-6", "SI-11"],
    "php-expose-phpinfo": ["CM-6", "SI-11"],
    "php-file-upload-no-validation": ["SI-10", "SC-18"],
    "php-hardcoded-credentials": ["SC-12", "SC-28", "IA-5"],
    "php-mt-rand-security": ["SC-13", "SC-12"],
    "php-open-redirect": ["SI-10", "SC-7"],
    "php-path-traversal-fopen": ["SI-10", "AC-3"],
    "php-path-traversal-unlink": ["SI-10", "AC-3"],
    "php-weak-hash-general": ["SC-13", "SC-12"],
    "php-xxe-dom": ["SI-10", "SC-4"],
    "php-xxe-simplexml": ["SI-10", "SC-4"],
    "php-rand-security": ["SC-13", "SC-12"],
    # ── C# (.NET) specific ─────────────────────────────────────────────
    "cs-binary-formatter": ["SI-10", "SI-16"],
    "cs-cors-allow-credentials-any": ["SC-7", "AC-4"],
    "cs-ecb-mode": ["SC-13", "SC-12"],
    "cs-ef-raw-sql": ["SI-10", "SI-16"],
    "cs-ef-raw-sql-concat": ["SI-10", "SI-16"],
    "cs-hardcoded-connection-string": ["SC-12", "SC-28", "IA-5"],
    "cs-hardcoded-password": ["SC-12", "SC-28", "IA-5"],
    "cs-ldap-injection": ["SI-10", "SI-16"],
    "cs-losformatter": ["SI-10", "SI-16"],
    "cs-newtonsoft-typenamehandling": ["SI-10", "SI-16"],
    "cs-soapformatter": ["SI-10", "SI-16"],
    "cs-sql-injection-concat": ["SI-10", "SI-16"],
    "cs-sql-injection-format": ["SI-10", "SI-16"],
    "cs-ssl-bypass": ["SC-8", "SC-13"],
    "cs-weak-crypto-des": ["SC-13", "SC-12"],
    "cs-xxe-dtd-enabled": ["SI-10", "SC-4"],
    "cs-command-injection": ["SI-10", "SI-16"],
    "cs-command-injection-cmd": ["SI-10", "SI-16"],
    "cs-command-injection-shell": ["SI-10", "SI-16"],
    "cs-cookie-no-httponly": ["SC-8", "SC-23"],
    "cs-cookie-no-secure": ["SC-8", "SC-23"],
    "cs-cors-allow-all": ["SC-7", "AC-4"],
    "cs-javascript-serializer": ["SI-10", "SI-16"],
    "cs-logging-sensitive": ["AU-3", "SI-11"],
    "cs-missing-antiforgery": ["SI-10", "SC-23"],
    "cs-path-traversal-directory": ["SI-10", "AC-3"],
    "cs-path-traversal-file": ["SI-10", "AC-3"],
    "cs-regex-injection": ["SC-5", "SI-10"],
    "cs-ssl-check-revocation": ["SC-8", "SC-13"],
    "cs-static-iv": ["SC-13", "SC-12"],
    "cs-unvalidated-redirect": ["SI-10", "SC-7"],
    "cs-weak-hash-md5": ["SC-13", "SC-12"],
    "cs-weak-hash-sha1": ["SC-13", "SC-12"],
    "cs-weak-password-hash": ["SC-13", "SC-12"],
    "cs-xss-html-raw": ["SI-10", "SI-16"],
    "cs-xss-htmlstring": ["SI-10", "SI-16"],
    "cs-xss-response-write": ["SI-10", "SI-16"],
    "cs-xxe-xmldocument": ["SI-10", "SC-4"],
    "cs-authorize-bypass": ["AC-3", "AC-6"],
    "cs-ssrf-httpclient": ["SI-10", "SC-7"],
    "cs-ssrf-webclient": ["SI-10", "SC-7"],
    "cs-viewbag-raw": ["SI-10", "SI-16"],
    "cs-weak-rng": ["SC-13", "SC-12"],
    "cs-xxe-xmlreader": ["SI-10", "SC-4"],
    # ── Go expansion (additional) ──────────────────────────────────────
    "go-bcrypt-cost-low": ["SC-13", "SC-12"],
    "go-body-not-closed": ["SC-24"],
    "go-context-background-http": ["SC-5", "SI-10"],
    "go-cookie-no-secure": ["SC-8", "SC-23"],
    "go-cors-wildcard": ["SC-7", "AC-4"],
    "go-ecb-mode": ["SC-13", "SC-12"],
    "go-error-string-compare": ["SI-11"],
    "go-filepath-join-dotdot": ["SI-10", "AC-3"],
    "go-gob-decode": ["SI-10", "SI-16"],
    "go-goroutine-loop-var": ["SA-11"],
    "go-http-default-client": ["SC-5", "SI-10"],
    "go-ldap-injection": ["SI-10", "SI-16"],
    "go-mutex-copy": ["SA-11"],
    "go-no-timeout": ["SC-5", "SI-10"],
    "go-reflect-call": ["SI-10", "SI-16"],
    "go-regex-injection": ["SC-5", "SI-10"],
    "go-regexp-compile-loop": ["SA-11"],
    "go-select-default-spin": ["SA-11"],
    "go-sql-join": ["SI-10", "SI-16"],
    "go-swallowed-error": ["SI-11"],
    "go-template-html-unescaped": ["SI-10", "SI-16"],
    "go-template-js-func": ["SI-10", "SI-16"],
    "go-test-fatal-goroutine": ["SA-11"],
    "go-waitgroup-add-inside": ["SA-11"],
    "go-weak-crypto-rc4": ["SC-13", "SC-12"],
    "go-weak-random": ["SC-13", "SC-12"],
    "go-append-prealloc": ["SA-11"],
    "go-bare-return-error": ["SI-11"],
    "go-bind-all-interfaces": ["SC-7", "CM-6"],
    "go-bool-param": ["SA-11"],
    "go-cgo-usage": ["SA-11"],
    "go-channel-deadlock": ["SA-11"],
    "go-context-todo": ["SA-11"],
    "go-defer-in-hot-path": ["SA-11"],
    "go-defer-os-exit": ["SC-24"],
    "go-empty-interface": ["SA-11"],
    "go-error-type-assert": ["SI-11"],
    "go-errors-new-fmt": ["SA-11"],
    "go-exported-no-doc": ["SA-11"],
    "go-file-not-closed": ["SC-24"],
    "go-float-equality": ["SA-11"],
    "go-fmt-sprintf-concat": ["SA-11"],
    "go-getter-prefix": ["SA-11"],
    "go-hardcoded-ip": ["CM-6"],
    "go-init-function": ["SA-11"],
    "go-integer-overflow": ["SI-16"],
    "go-ioutil-deprecated": ["SA-11"],
    "go-json-marshal-loop": ["SA-11"],
    "go-json-number-overflow": ["SI-16"],
    "go-large-struct-value": ["SA-11"],
    "go-log-injection": ["AU-9", "SI-10"],
    "go-magic-number": ["SA-11"],
    "go-map-prealloc": ["SA-11"],
    "go-naked-return": ["SA-11"],
    "go-nil-interface-method": ["SI-16"],
    "go-nil-slice-append": ["SA-11"],
    "go-no-csrf": ["SI-10", "SC-23"],
    "go-once-reset": ["SA-11"],
    "go-recover-all": ["SI-11"],
    "go-rows-not-closed": ["SC-24"],
    "go-string-contains-loop": ["SA-11"],
    "go-string-index-rune": ["SA-11"],
    "go-stuttering-name": ["SA-11"],
    "go-sync-pool-new": ["SA-11"],
    "go-test-parallel-shared": ["SA-11"],
    "go-ticker-not-stopped": ["SC-24"],
    "go-time-equal": ["SA-11"],
    "go-time-now-loop": ["SA-11"],
    "go-todo-fixme": ["SA-11"],
    "go-underscore-name": ["SA-11"],
    "go-unsafe-sizeof": ["SA-11"],
    "go-unvalidated-redirect-url": ["SI-10", "SC-7"],
    "go-xml-external-entity": ["SI-10", "SC-4"],
    "go-zip-slip": ["SI-10", "AC-3"],
    # ── Express / Node.js expansion ────────────────────────────────────
    "express-session-no-httponly": ["SC-8", "SC-23"],
    "express-session-no-secure": ["SC-8", "SC-23"],
    # ── Next.js expansion ──────────────────────────────────────────────
    "nextjs-api-no-auth": ["AC-3", "AC-6"],
    # ── Python XXE / XML ───────────────────────────────────────────────
    "lxml-parse-untrusted": ["SI-10", "SC-4"],
    "xml-sax-parser": ["SI-10", "SC-4"],
    "elementtree-defused": ["SI-10", "SC-4"],
    "xml-parse-untrusted": ["SI-10", "SC-4"],
}


def get_cwe(rule: str) -> str | None:
    """Return the CWE ID for a rule name, or None if unmapped."""
    return CWE_MAP.get(rule)


def get_nist(rule: str) -> list[str]:
    """Return NIST SP 800-53 controls for a rule name, or empty list."""
    return NIST_MAP.get(rule, [])
